CREATE TABLE IF NOT EXISTS public.equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name TEXT NOT NULL,
    category TEXT NOT NULL,
    asset_code TEXT UNIQUE NOT NULL,
    condition TEXT DEFAULT 'Good' CHECK (condition IN ('Good', 'Fair', 'Needs Repair', 'Damaged')),
    availability TEXT DEFAULT 'Available' CHECK (availability IN ('Available', 'Borrowed', 'Under Maintenance')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.borrow_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL REFERENCES public.equipment(id) ON DELETE RESTRICT,
    borrower_name TEXT NOT NULL,
    borrower_type TEXT NOT NULL CHECK (borrower_type IN ('Student', 'Faculty', 'Staff')),
    department TEXT NOT NULL,
    date_borrowed DATE DEFAULT CURRENT_DATE NOT NULL,
    due_date DATE NOT NULL,
    date_returned DATE,
    status TEXT DEFAULT 'Borrowed' CHECK (status IN ('Borrowed', 'Returned')),
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_equipment_asset_code ON public.equipment(asset_code);
CREATE INDEX IF NOT EXISTS idx_equipment_availability ON public.equipment(availability);
CREATE INDEX IF NOT EXISTS idx_transactions_equipment_id ON public.borrow_transactions(equipment_id);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON public.borrow_transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_borrower_name ON public.borrow_transactions(borrower_name);

ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.borrow_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to view equipment"
ON public.equipment
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to insert equipment"
ON public.equipment
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update equipment"
ON public.equipment
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete equipment"
ON public.equipment
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to view borrow transactions"
ON public.borrow_transactions
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to insert borrow transactions"
ON public.borrow_transactions
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update borrow transactions"
ON public.borrow_transactions
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete borrow transactions"
ON public.borrow_transactions
FOR DELETE
TO authenticated
USING (true);

INSERT INTO public.equipment (equipment_name, category, asset_code, condition, availability)
VALUES 
    ('Epson Projector', 'Projector', 'PROJ-001', 'Good', 'Available'),
    ('Acer Laptop', 'Laptop', 'LAP-002', 'Good', 'Available'),
    ('Canon Camera', 'Camera', 'CAM-001', 'Fair', 'Available'),
    ('Wireless Microphone', 'Microphone', 'MIC-001', 'Good', 'Available'),
    ('TP-Link Router', 'Router', 'ROUT-001', 'Good', 'Available')
ON CONFLICT (asset_code) DO NOTHING;
